# What program(s) have to be built
PROGRAMS = ex5

# Dependencies for the program(s) to build
# 5.1
# ex5: ../common/remregs.o ../common/wperror.o ../common/robot.o ../common/utils.o ex51.o
# 5.2
ex5: ../common/remregs.o ../common/wperror.o ../common/robot.o ex52.o

# Includes the common Makefile with the various rules
include ../common/Makefile.inc
